[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"
# Force rebuild by adding a build arg
buildArgs = { "BUILD_DATE" = "2024-06-28" }

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
# Skip build cache
noBuildCache = true