apiVersion: v1
kind: Namespace
metadata:
  name: pup-ai
  labels:
    app: pup-ai
    environment: production
    monitoring: enabled
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pup-ai-quota
  namespace: pup-ai
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    limits.cpu: "200"
    limits.memory: "400Gi"
    persistentvolumeclaims: "10"
    services: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pup-ai-limits
  namespace: pup-ai
spec:
  limits:
  - max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    type: Container