apiVersion: v1
kind: Secret
metadata:
  name: pup-ai-secrets
  namespace: pup-ai
  labels:
    app: pup-ai
    component: secrets
type: Opaque
stringData:
  # Slack credentials - REPLACE WITH BASE64 ENCODED VALUES
  SLACK_BOT_TOKEN: "xoxb-your-token-here"
  SLACK_APP_TOKEN: "xapp-your-token-here"
  SLACK_SIGNING_SECRET: "your-signing-secret"
  MY_USER_ID: "your-user-id"
  
  # OpenAI credentials - REPLACE WITH BASE64 ENCODED VALUES
  OPENAI_API_KEY: "sk-your-api-key"
  
  # Database connection - REPLACE WITH BASE64 ENCODED VALUES
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/pupai?sslmode=require"
  
  # Redis connection - REPLACE WITH BASE64 ENCODED VALUES
  REDIS_URL: "redis://:password@redis-service:6379"
---
# External Secrets Operator integration (recommended for production)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: pup-ai
spec:
  provider:
    vault:
      server: "https://vault.company.com:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "pup-ai"
          serviceAccountRef:
            name: "pup-ai"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pup-ai-secrets
  namespace: pup-ai
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: pup-ai-secrets
    creationPolicy: Owner
  data:
  - secretKey: SLACK_BOT_TOKEN
    remoteRef:
      key: pup-ai/slack
      property: bot_token
  - secretKey: SLACK_APP_TOKEN
    remoteRef:
      key: pup-ai/slack
      property: app_token
  - secretKey: SLACK_SIGNING_SECRET
    remoteRef:
      key: pup-ai/slack
      property: signing_secret
  - secretKey: OPENAI_API_KEY
    remoteRef:
      key: pup-ai/openai
      property: api_key
  - secretKey: DATABASE_URL
    remoteRef:
      key: pup-ai/database
      property: connection_string
  - secretKey: REDIS_URL
    remoteRef:
      key: pup-ai/redis
      property: connection_string