apiVersion: v1
kind: Service
metadata:
  name: pup-ai
  namespace: pup-ai
  labels:
    app: pup-ai
    component: bot
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: ClusterIP
  selector:
    app: pup-ai
    component: bot
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  sessionAffinity: None
---
# Headless service for peer discovery
apiVersion: v1
kind: Service
metadata:
  name: pup-ai-headless
  namespace: pup-ai
  labels:
    app: pup-ai
    component: bot
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: pup-ai
    component: bot
  ports:
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
---
# ServiceMonitor for Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pup-ai
  namespace: pup-ai
  labels:
    app: pup-ai
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      app: pup-ai
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    honorLabels: true
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
---
# HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pup-ai-hpa
  namespace: pup-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pup-ai
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  # Custom metrics
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  - type: Pods
    pods:
      metric:
        name: response_time_p95
      target:
        type: AverageValue
        averageValue: "500m"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
---
# PodDisruptionBudget for high availability
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pup-ai-pdb
  namespace: pup-ai
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: pup-ai
      component: bot
  unhealthyPodEvictionPolicy: AlwaysAllow