apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pup-ai

bases:
  - ../../

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

configMapGenerator:
  - name: pup-ai-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - NODE_ENV=production
      - DATABASE_POOL_SIZE=50
      - REDIS_CONNECTION_POOL_SIZE=20
      - WORKER_CONCURRENCY=10

replicas:
  - name: pup-ai
    count: 5
  - name: pup-ai-workers
    count: 3

images:
  - name: your-registry.com/pup-ai
    newTag: v2.0.0-prod

resources:
  - production-resources.yaml